//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TnpExpressions.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TnpExpressionsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface ITnpExpressionsListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.tnp_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTnp_expression([NotNull] TnpExpressionsParser.Tnp_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.tnp_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTnp_expression([NotNull] TnpExpressionsParser.Tnp_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] TnpExpressionsParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] TnpExpressionsParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] TnpExpressionsParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] TnpExpressionsParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] TnpExpressionsParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] TnpExpressionsParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] TnpExpressionsParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] TnpExpressionsParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.qualified_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualified_identifier([NotNull] TnpExpressionsParser.Qualified_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.qualified_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualified_identifier([NotNull] TnpExpressionsParser.Qualified_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] TnpExpressionsParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] TnpExpressionsParser.IdentifierContext context);
}
