//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TnpExpressions.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITnpExpressionsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TnpExpressionsBaseListener : ITnpExpressionsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.tnp_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTnp_expression([NotNull] TnpExpressionsParser.Tnp_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.tnp_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTnp_expression([NotNull] TnpExpressionsParser.Tnp_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] TnpExpressionsParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] TnpExpressionsParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] TnpExpressionsParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] TnpExpressionsParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] TnpExpressionsParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] TnpExpressionsParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] TnpExpressionsParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] TnpExpressionsParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.qualified_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualified_identifier([NotNull] TnpExpressionsParser.Qualified_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.qualified_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualified_identifier([NotNull] TnpExpressionsParser.Qualified_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TnpExpressionsParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] TnpExpressionsParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TnpExpressionsParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] TnpExpressionsParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
